name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Post Job Cleanup
      run: |
        echo "Running cleanup"
        git config --global --add safe.directory /Users/runner/work/WellNest/WellNest || :
        git config --local --unset-all http.https://github.com/.extraheader || :
      if: always() # Run this step even if previous steps failed
